### ISSUE TITLE
Not working when `ssr: false`

### ISSUE THREAD

**Issue by ennioVisco** [Mini-ghost/nuxt-parallel-limit#7]
Hello,

From some preliminary tests it seems it does not work when ssr is false, and the code seems to confirm it:
https://github.com/Mini-ghost/nuxt-parallel-limit/blob/39db9ea165a5549263874d5a2d004e58cde63cb7/src/runtime/plugin.ts#L41

Is there any specific reason for this?

**Comment by Mini-ghost** [comment]
@ennioVisco Thank for your issues.

Hi, I tried to invoke the API that matches the pattern in the config ten times using `$fetch` within a for loop and watched the developer tools. I found that it works.

**nuxt.config.ts**

```ts
export default defineNuxtConfig({
  ssr: false,
  modules: ['nuxt-parallel-limit'],
  parallelLimit: {
    patterns: [
      {
        pattern: 'https://jsonplaceholder.typicode.com',
        limit: 2
      }
    ]
  }
})

```

**index.vue**

```vue
<script setup lang="ts">
Array.from({ length: 10 }, (_, i) => i + 1).forEach((i) => {
  $fetch(`https://jsonplaceholder.typicode.com/comments`)
});
</script>
```

**Chrome DevTools**

<img width="1552" alt="截圖 2023-08-05 下午1 10 01" src="https://github.com/Mini-ghost/nuxt-parallel-limit/assets/39984251/f6a50468-9cac-4cb2-89a3-b643a5e0bb19">

---

https://github.com/Mini-ghost/nuxt-parallel-limit/blob/39db9ea165a5549263874d5a2d004e58cde63cb7/src/runtime/plugin.ts#L12

https://github.com/Mini-ghost/nuxt-parallel-limit/blob/39db9ea165a5549263874d5a2d004e58cde63cb7/src/runtime/plugin.ts#L41-L43

The code you extracted is to ensure that `$fetch` is only processed once because `nuxt-parallel-limit` directly processes `globalThis.$fetch`, so it only needs to be processed once.

**Comment by ennioVisco** [comment]
> @ennioVisco Thank for your issues.
> 
> Hi, I tried to invoke the API that matches the pattern in the config ten times using `$fetch` within a for loop and watched the developer tools. I found that it works.
> 
> **nuxt.config.ts**
> 
> ```ts
> export default defineNuxtConfig({
>   ssr: false,
>   modules: ['nuxt-parallel-limit'],
>   parallelLimit: {
>     patterns: [
>       {
>         pattern: 'https://jsonplaceholder.typicode.com',
>         limit: 2
>       }
>     ]
>   }
> })
> ```
> 
> **index.vue**
> 
> ```
> <script setup lang="ts">
> Array.from({ length: 10 }, (_, i) => i + 1).forEach((i) => {
>   $fetch(`https://jsonplaceholder.typicode.com/comments`)
> });
> </script>
> ```
> 
> **Chrome DevTools**
> 
> <img alt="截圖 2023-08-05 下午1 10 01" width="1552" src="https://user-images.githubusercontent.com/39984251/258564856-f6a50468-9cac-4cb2-89a3-b643a5e0bb19.png">
> https://github.com/Mini-ghost/nuxt-parallel-limit/blob/39db9ea165a5549263874d5a2d004e58cde63cb7/src/runtime/plugin.ts#L12
> 
> https://github.com/Mini-ghost/nuxt-parallel-limit/blob/39db9ea165a5549263874d5a2d004e58cde63cb7/src/runtime/plugin.ts#L41-L43
> 
> The code you extracted is to ensure that `$fetch` is only processed once because `nuxt-parallel-limit` directly processes `globalThis.$fetch`, so it only needs to be processed once.

Hey thanks for the help! I actually tested the use case a few hours ago and I can confirm it works in the playground. I'm still digging to understand what is causing the problem in our project 

One question though, why did you use `$fetch` instead of `useFetch`?

**Comment by Mini-ghost** [comment]
The reason is that not all requests use `useFetch`. Maybe we will upload files through `$fetch`, or we will not use `useFetch` when we write APIs in the server directory but use `$fetch`.

For the above reasons `nuxt-parallel-limit` chooses to process `$fetch` instead of `useFetch`, hope this answer helps you.
